---
title: "Bristol temperature project"
author: "Sara Irish"
date: "2025-12-17"
output: html_document
---



# Setup 
```{r}
suppressPackageStartupMessages({
  library(glmmTMB)
  library(car)
  library(popbio)
  library(ggplot2)
  library(ggbeeswarm)
  library(shades)
  library(RColorBrewer)
  library(DHARMa)
  library(Rmisc)
  library(dabestr)
  library(magrittr)
  library(tidyr)
  library(dplyr)
  library(ggeffects)
  library(lme4)
  library(optimx)
  library(nloptr)
  library(dfoptim)
  library(data.table)
  library(DHARMa)
  library(emmeans)
  library(ggpubr)
  library(patchwork)
  library(lubridate)
  library(performance)
  library(dplyr)#to check overdispersion in glmmTMB models
  library(survival)
  library(coxme) #for cox model
  library(purrr) #for forestplot
  library(ggpubr) #for forestplot
  library(survminer) #for forestplot
  library(AICcmodavg)
  library(forcats)
  library(fields) #for thin plate spline plots
  library(usethis)
  library(gitcreds)
  library(httr2)
  library(readr)
  library(Hmisc)
})

R.version

#Lifespan data for N2s + daf-16 and skn-1 mutants
mut_LS <- read.csv('Bristol_LS_mut.csv')

#read in full reproduction dataset
repro_mut <- read.csv('Bristol_repro_mut.csv')

#read in temperature data
temp <- read.csv('Bristol_temp.csv')



#create level order for 10 days reproduction
level_order <- c('D1', 'D2', 'D3', 'D4','D5','D6','D7','D8','D9','D10')

#create italicized lables for daf-2 and mutant names
daf_label <- expression(italic("daf-2"))
daf16_label <- expression(italic("    daf-16"))
skn1_label <- expression(italic("    skn-1"))

#plot margins for dabestr plots
left_right_margin <- theme(plot.margin = unit(c(0, 0.4, 0, 0.4), 'cm'))

```

## N2s + SKN-1 and DAF-16 Mutants - format data
```{r}

#put reproduction data in long form
mut_long <- repro_mut %>% 
  pivot_longer(
    cols = `D1`:`D15`, 
    names_to = "Day",
    values_to = "value"
)

#If matricide, change NAs to 0 (these were incorrectly input)
mut_long$value <- ifelse(mut_long$Matricide == 1 & is.na(mut_long$value), 0, mut_long$value)

#make day a factor for plotting
mut_long$Day <- as.factor(mut_long$Day)

#set level order
levels(mut_long$Day) <- list('1' = 'D1', '2' = 'D2', '3' = 'D3', '4' = 'D4', '5' = 'D5', '6' = 'D6', '7' = 'D7', '8' = 'D8', '9' = 'D9', '10' = 'D10', '11' = 'D11', '12' = 'D12', '13' = 'D13', '14' = 'D14', '15' = 'D15')

#set treatment levels as control and daf-2
mut_long$Treatment <- as.factor(mut_long$Treatment)
mut_long$Treatment <- revalue(mut_long$Treatment, c('ev' = 'control', 'daf'='daf-2'))
mut_long$Treatment <- relevel(mut_long$Treatment, "control")

#Split dataset by strain
SKN <- mut_long %>% 
  filter(Strain == 'SKN')

DAF16 <- mut_long %>% 
  filter(Strain == 'DAF16')

N2 <- mut_long %>%
  filter(Strain == 'N2')

#fix treatment names and set control as reference level for lifespan data
mut_LS$Treatment <- as.factor(mut_LS$Treatment)
mut_LS$Treatment <- revalue(mut_LS$Treatment, c('EV' = 'control', 'DAF-2'='daf-2'))
mut_LS$Treatment <- relevel(mut_LS$Treatment, "control")
levels(mut_LS$Treatment)


```

## N2 reproduction
```{r}

#Age-specific reproduction plot
N2_rep <-ggplot(data=N2, aes(x=factor(Day), y=value, group=Treatment, color=Treatment))+
  geom_jitter(alpha = 0.2, position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.5))+
  stat_summary(fun.data="mean_cl_boot", geom="errorbar", size = 1, width=0.0, position = position_dodge(0.5)) +
  stat_summary(fun.data="mean_cl_boot", geom="point", size = 3, position = position_dodge(0.5)) +
  stat_summary(fun.data="mean_cl_boot", geom="line",  size=1, position = position_dodge(0.5)) +
  theme_classic()+
  labs(y="Offspring number", x="Day", size=13)+
  labs(col="")+
  labs(title = '    N2')+
  theme(axis.title.y = element_text(size=14),
        axis.text.y = element_text(size = 12))+
  theme(axis.title.x = element_text(size=14),
        axis.text.x = element_text(size = 12),
        title = element_text(size = 14))+
  theme(legend.text = element_text(size = 12))+
  scale_color_manual(values=c('#E64B35FF','#4DBBD5FF'), labels = c('ev',daf_label))+
  theme(legend.key.width = unit(0.5,"cm"))+
  coord_cartesian(ylim = c(0,85))+
  theme(legend.position = c(0.8,0.9))
 
 N2_rep
 
 #################
 ## Calculate individual fitness (lambda)
 #########################
 
#Format data for Leslie matrix calculations 
 N2_wide <- spread(N2, Day, value)

#remove unnecessary column
within(N2_wide, rm(Strain))

#create empty matrix
L <- matrix(nrow = nrow(N2_wide), ncol = 3)

#loop to calculate lambda per individual
for (i in 1:nrow(N2_wide)){
  Les <- matrix(0, ncol = 9, nrow = 9)
  diag(Les[-1,]) <- rep(1, 8) # add the 1s for survival probability diagonally
  Fert <- c(0,0, as.numeric(as.vector(N2_wide[i,][4:10]))) #the columns in data that has the reproductive counts
  Fert[is.na(Fert)] <- 0 #makes all NAs into 0s
  Les[1,] <- c(Fert)
  class(Les) <- "leslie.matrix"
  Lambda <- popbio::eigen.analysis(Les)$lambda1
  L[i, 1:3] <- c(paste0(N2_wide$Treatment[i]), paste0(N2_wide$ID[i]), Lambda)
  
}

#change column names of created dataset
colnames(L)<-c("Treatment", "ID", "Lambda")

#make sure the new data is in dataframe form
Data<-as.data.frame(L)

#make sure lambda is numeric
Data$Lambda<-as.numeric(as.character(Data$Lambda))

#create dabestr object for plot
Lambda_N2 <-
  Data %>%
  load(Treatment, Lambda,
         idx = list(c("control", "daf-2")))


## Lambda dabestr plot
Lambda_plot_N2 <- dabest_plot(mean_diff(Lambda_N2), TRUE, swarm_label = 'Lambda', raw_marker_spread = 1, custom_palette = 'npg', swarm_x_text = 12, swarm_y_text = 12, contrast_y_text = 12, contrast_x_text = 12, raw_marker_alpha = 0.3, tufte_size = 1)

Lambda_plot_N2

####################
# calculate lifetime reproductive success (LRS)
##################

# calculate total number offspring produced per individual
totalrep<-na.omit(as.data.frame.table(tapply(N2$value,list(N2$Treatment, N2$ID),sum)))

# change column names
names(totalrep)<-c("Treatment", "Replicate", "Totrep")

#create dabestr object
Totrep <-
  totalrep %>%
  load(Treatment, Totrep,
         idx = c('control','daf-2'))

#dabestr plot
LRS_N2 <- dabest_plot(mean_diff(Totrep), TRUE, swarm_label = 'LRS', raw_marker_spread = 1, custom_palette = 'npg', swarm_x_text = 12, swarm_y_text = 12, contrast_y_text = 12, contrast_x_text = 12, raw_marker_alpha = 0.3, tufte_size = 1)
LRS_N2


#combine N2 reproduction plots
N2_repro <- ggarrange(N2_rep+theme(plot.margin = unit(c(0, 1, 0, 0.3), 'cm')), 
          ggarrange(Lambda_plot_N2+left_right_margin , LRS_N2+left_right_margin, ncol = 2, labels = c('B','C')),
          nrow = 2, heights = c(1.4,1), common.legend = T, labels = c('A',''))

N2_repro

```

## Analyse N2 reproduction
```{r}
#set day as numeric variable to square for quadratic term
N2$Day <- as.numeric(N2$Day)
N2$Day2 <- (N2$Day)^2

#set reference level to ev
N2$Treatment <- as.factor(N2$Treatment)
N2$Treatment <- relevel(N2$Treatment, ref = 'ev')

#try nbinom2 first with Day^2 included as predictor
m1 <- glmmTMB(value ~ Treatment*Day2+Treatment*Day + (1|ID), family = nbinom2(), data = N2)
summary(m1)
sim_m1 <- simulateResiduals(m1, plot = T)
testDispersion(sim_m1) #underdispersion
testZeroInflation(sim_m1)#zero inflation issues

#try including ziformula
m2 <- glmmTMB(value ~ Treatment*Day2+Treatment*Day + (1|ID), ziformula = ~Treatment*Day, family = nbinom2(), data = N2)
summary(m2)
sim_m2 <- simulateResiduals(m2, plot = T)
testZeroInflation(sim_m2)#still major zero inflation
AIC(m1, m2)

#try day^2 in ziformula
m3 <- glmmTMB(value ~ Treatment*Day2 + Treatment*Day + (1|ID), ziformula = ~Treatment*Day2, family = nbinom2(), data = N2)
summary(m3)
AIC(m2, m3)
sim_m3 <- simulateResiduals(m3, plot = T)
testZeroInflation(sim_m3)#no improvement


###Final model
#higher AIC, but majorly improved dispersion and zeroinflation
m4 <- glmmTMB(value ~ Treatment*Day2 + Treatment*Day +(1|ID), ziformula = ~Treatment*Day2,family = poisson, data = N2)
AIC(m3, m4)
sim_m4 <- simulateResiduals(m4, plot = T)
testZeroInflation(sim_m4)
testDispersion(sim_m4)
summary(m4)
Anova(m4, type = 'III')
##==

m5 <- glmmTMB(value ~ Treatment*Day2 + Treatment*Day +(1|ID), ziformula = ~Day2,family = poisson, data = N2)
AIC(m4, m5)#slightly higher
sim_m5 <- simulateResiduals(m5, plot = T)
testZeroInflation(sim_m5)#no change
testDispersion(sim_m5)#no change
summary(m5)


#analyse total reproduction
hist(totalrep$Totrep)
#set reference level to ev
totalrep$Treatment <- as.factor(totalrep$Treatment)
totalrep$Treatment <- relevel(totalrep$Treatment, ref = 'ev')

#analyse LRS
LRS_m1 <- lm(Totrep ~ Treatment, data = totalrep)
summary(LRS_m1)
Anova(LRS_m1, type = 'II')
#analyse lambda
hist(Data$Lambda)
lambda_m1 <- lm(Lambda ~ Treatment, data = Data)
summary(lambda_m1)
Anova(lambda_m1, type = 'II')

```

## N2 lifespan
```{r}
#N2 lifespan data only
N2_LS <- mut_LS %>%
  filter(Strain == 'N2')


#create survival object for N2
surv<-survfit(Surv(Age,Event)~Treatment,data=N2_LS)

#survival plot
N2_LS_plot <-ggsurvplot(surv, ylab="Survival probability", data = N2_LS, size= 0.8, font.ylab= 13, font.xlab= 13, legend = 'none', legend.labs = c( "ev", "daf-2"), 
legend.title = "", title = "    N2", censor = FALSE, xlab = "Day", xlim=c(0,85), break.time.by = 10, position= position_dodge(0.9), font.tickslab = c(12))

#add colours and labels
N2_LS_plot <- N2_LS_plot$plot+
  scale_colour_manual(labels = c('control',daf_label), , values = c('#E64B35FF','#4DBBD5FF'))

N2_LS_plot


#Censor matricides
N2_LS_matcen <- N2_LS %>%
  filter(Cause != 'M')

#create survival object
surv<-survfit(Surv(Age,Event)~Treatment,data=N2_LS_matcen)

#create survival plot
N2_LS_matcen_plot <-ggsurvplot(surv, ylab="Survival probability", data = N2_LS_matcen, size= 0.8, font.ylab= 13, font.xlab= 13, legend = 'none', legend.labs = c( "ev", "daf-2"),  legend.title = "", title = "    N2", censor = FALSE, xlab = "Day", xlim=c(0,85), break.time.by = 10, position= position_dodge(0.9), font.tickslab = c(12), font.legend = c(13))

#add colours and labels
N2_LS_matcen_plot <- N2_LS_matcen_plot$plot+
  scale_colour_manual(labels = c('ev',daf_label), , values = c('#E64B35FF','#4DBBD5FF'))

N2_LS_matcen_plot


#function to create forest plot
meforest <- function(cox, control){ 
  require(AICcmodavg)
  require(ggplot2)
  require(forcats)
  store <- matrix(nrow = length(cox$coefficients) + 1, ncol = 4)
  ref <- c(paste(control), 0, NA, NA)
  store[1,] <- ref
  for (x in 1:length(cox$coefficients)){
    y = x+1
    mean<-cox$coefficients[x]
    emean <- (mean)
    CIL <- cox$coefficients[x] - (1.96*extractSE(cox)[x])
    CUL <- cox$coefficients[x] + (1.96*extractSE(cox)[x])
    eCIL <- (CIL)
    eCUL <- (CUL)
    store[y, 1:4] <- c(names(cox$coefficients[x]), emean, eCIL, eCUL)}
  colnames(store) <- c("Treatment_ID", "mean", "CIL","CUL")
  store <- as.data.frame(store)
  store$mean <- as.numeric(as.character(store$mean))
  store$CIL <- as.numeric(as.character(store$CIL))
  store$CUL <- as.numeric(as.character(store$CUL))
  forest<-ggplot(store, aes(x = mean, xmax = CUL, xmin = CIL, y = Treatment_ID, colour = Treatment_ID)) +
    geom_point(size=2, shape = 19, colour = c('#E64B35FF','#4DBBD5FF')) +
    geom_errorbarh(height=0.25, size=0.8,  colour = c('#E64B35FF','#4DBBD5FF')) +
    theme_minimal() +
    geom_vline(xintercept=0, linetype="dotted", size=0.8) +
    xlab("Hazard Ratio")+
    ylab("")+
      theme(
      axis.text = element_text(size = 12),
      axis.title = element_text(size = 13))+
    scale_y_discrete(limits = (levels(store$Treatment_ID)), labels = c('control',daf_label))+
    expand_limits(x = c(-1.5,0.5))
  return(forest)
}



#Analysis with cox proportional hazards models - create forest plots with analysis
cox_N2 <- coxme(Surv(Age, Event) ~ Treatment + (1|Plate.ID), data = N2_LS)
summary(cox_N2)
plot(cox.zph(cox_N2))#analysis for this will be messy due to effects of matricide

#create forest plot from cox model with coxme function
forest_N2 <- meforest(cox_N2, 'control')
forest_N2

#Use emmeans because of negligible effect of plate.ID
N2_emm <- emmeans(cox_N2, ~ Treatment)  # EMMs of treatment 
N2_emm

#Get contrasts
contrasts_N2 <- contrast(N2_emm, method = "revpairwise")

#make a dataframe out of the contrast summary
df_N2 <- as.data.frame(summary(contrasts_N2, infer = TRUE))

# Rename columns
names(df_N2)[names(df_N2) == "estimate"] <- "logHR"
df_N2$HR <- exp(df_N2$logHR)
df_N2$lower.HR <- exp(df_N2$asymp.LCL)
df_N2$upper.HR <- exp(df_N2$asymp.UCL)

#fix labels
df_N2$Comparison <- df_N2$contrast

#Create forest plot for differences of treatments within strains
N2_contrasts <- ggplot(df_N2, aes(x = Comparison, y = logHR)) +
  geom_point(size = 4, color = '#4DBBD5FF') +
  geom_hline(yintercept = 0, linetype = "dashed", size = 1.2, color = '#E64B35FF', linewidth = 0.8) +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL), width = 0.2, size = 1.1,color ='#4DBBD5FF')+
  coord_flip() +
  scale_x_discrete(labels = c(''))+
  labs(
    title = "",
    x = "",
    y = "Log hazard ratio (HR)"
  ) +
  theme_minimal(base_size = 12)+
  theme(axis.text = element_text(size = 13),
        axis.title = element_text(size = 14),
      axis.line.x = ggplot2::element_line(color = "black", size = 0.5),
      axis.line.y = ggplot2::element_line(color = "black", size = 0.5),
        legend.position = 'none')

N2_contrasts



#Analysis with cox proportional hazards models - create forest plots with analysis
cox_N2_matcen <- coxme(Surv(Age, Event) ~ Treatment + (1|Plate.ID), data = N2_LS_matcen)
plot(cox.zph(cox_N2_matcen))#better than when matricides are excluded
cox.zph(cox_N2_matcen)#OK
summary(cox_N2_matcen)

#create forest plot from cox model with function

forest_N2_matcen <- meforest(cox_N2_matcen, 'control')
forest_N2_matcen

#Use emmeans because of negligible effect of plate.ID
N2_NM_emm <- emmeans(cox_N2_matcen, ~ Treatment)  # EMMs of treatment 
N2_NM_emm

#Get contrasts
contrasts_N2_NM <- contrast(N2_NM_emm, method = "revpairwise")

#make a dataframe out of the contrast summary
df_N2_NM <- as.data.frame(summary(contrasts_N2_NM, infer = TRUE))

# Rename columns
names(df_N2_NM)[names(df_N2_NM) == "estimate"] <- "logHR"
df_N2_NM$HR <- exp(df_N2_NM$logHR)
df_N2_NM$lower.HR <- exp(df_N2_NM$asymp.LCL)
df_N2_NM$upper.HR <- exp(df_N2_NM$asymp.UCL)

#fix labels
df_N2_NM$Comparison <- df_N2_NM$contrast

#Create forest plot for differences of treatments within strains
N2_NM_contrasts <- ggplot(df_N2_NM, aes(x = Comparison, y = logHR)) +
  geom_point(size = 4, color = '#4DBBD5FF') +
  geom_hline(yintercept = 0, linetype = "dashed", size = 1.2, color = '#E64B35FF', linewidth = 0.8) +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL), width = 0.2, size = 1.1,color ='#4DBBD5FF')+
  coord_flip() +
  scale_x_discrete(labels = c(''))+
  labs(
    title = "",
    x = "",
    y = "Log hazard ratio (HR)"
  ) +
  theme_minimal(base_size = 12)+
  theme(axis.text = element_text(size = 13),
        axis.title = element_text(size = 14),
      axis.line.x = ggplot2::element_line(color = "black", size = 0.5),
      axis.line.y = ggplot2::element_line(color = "black", size = 0.5),
        legend.position = 'none')

N2_NM_contrasts


#Combine plots with and without matricides
N2_mat_inc <- ggarrange(N2_LS_plot, N2_contrasts+theme(plot.margin = margin(t = 0, r = 0.15, b = 0, l = 0.75, unit = "cm")), nrow = 2, ncol = 1, heights = c(2,1), labels = c('A','D'))
N2_mat_inc

N2_mat_exc <- ggarrange(N2_LS_matcen_plot, N2_NM_contrasts+theme(plot.margin = margin(t = 0, r = 0.15, b = 0, l = 0.75, unit = "cm")), nrow = 2, ncol = 1, heights = c(2,1), labels = c('A','D'))
N2_mat_exc
 
```

##SKN-1 mutant reproduction 
```{r}

#age-specific reproduction plot
 SKN_rep <-ggplot(data=SKN, aes(x=factor(Day), y=value, group=Treatment, color=Treatment))+
  geom_jitter(alpha = 0.2, position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.5))+
  stat_summary(fun.data="mean_cl_boot", geom="errorbar", size = 1, width=0.0, position = position_dodge(0.5)) +
  stat_summary(fun.data="mean_cl_boot", geom="point", size = 3, position = position_dodge(0.5)) +
  stat_summary(fun.data="mean_cl_boot", geom="line",  size=1, position = position_dodge(0.5)) +
  theme_classic()+
  labs(y="Offspring number", x="Day", size=13)+
  labs(col="")+
  labs(title = skn1_label)+
  theme(axis.title.y = element_text(size=14),
        axis.text.y = element_text(size = 12))+
  theme(axis.title.x = element_text(size=14), 
        axis.text.x = element_text(size = 12),
        legend.text = element_text(size = 12),
        title = element_text(size = 14))+
  scale_color_manual(values=c('#E64B35FF','#4DBBD5FF'), labels = c('ev',daf_label))+
  theme(legend.key.width = unit(0.5,"cm"))+
  coord_cartesian(ylim = c(0,70))+
  theme(legend.position = c(0.8,0.9))

SKN_rep


#####################
# calculate individual fitness
####################

#put data back into wide form
SKN_wide <- spread(SKN, Day, value)

#remove unnecessary columns for ease
within(SKN_wide, rm(Strain))

#create empty matrix
L <- matrix(nrow = nrow(SKN_wide), ncol = 3)

#loop to calculate lambda
for (i in 1:nrow(SKN_wide)){
  Les <- matrix(0, ncol = 9, nrow = 9)
  diag(Les[-1,]) <- rep(1, 8) # add the 1s for survival probability diagonally
  Fert <- c(0,0, as.numeric(as.vector(SKN_wide[i,][4:10]))) #the columns in data that has the reproductive counts
  Fert[is.na(Fert)] <- 0 #makes all NAs into 0
  Les[1,] <- c(Fert)
  class(Les) <- "leslie.matrix"
  Lambda <- popbio::eigen.analysis(Les)$lambda1
  L[i, 1:3] <- c(paste0(SKN_wide$Treatment[i]), paste0(SKN_wide$ID[i]), Lambda)
  
}

#change column names
colnames(L)<-c("Treatment", "ID", "Lambda")

#make calculations a dataframe
SKN_Data<-as.data.frame(L)

#make sure lambda is numeric
SKN_Data$Lambda<-as.numeric(as.character(SKN_Data$Lambda))

#create dabestr object
Lambda_SKN <-
  SKN_Data %>%
  load(Treatment, Lambda,
         idx = list(c("control", "daf-2")))

## Lambda dabestr plot
Lambda_plot_SKN <- dabest_plot(mean_diff(Lambda_SKN), TRUE, swarm_label = 'Lambda', raw_marker_spread = 1, custom_palette = 'npg', swarm_x_text = 12, swarm_y_text = 12, contrast_y_text = 12, contrast_x_text = 12, raw_marker_alpha = 0.3, tufte_size = 1)

Lambda_plot_SKN


#######################
# calculate lifetime reproduction success (LRS)
######################

#calculate total offspring produced per offspring
SKN_totalrep<-na.omit(as.data.frame.table(tapply(SKN$value,list(SKN$Treatment, SKN$ID),sum)))

#change column names
names(SKN_totalrep)<-c("Treatment", "Replicate", "Totrep")

#create dabestr object
SKN_Totrep <-
  SKN_totalrep %>%
  load(Treatment, Totrep,
         idx = c('control','daf-2'))

#create LRS dabestr plot
LRS_SKN <- dabest_plot(mean_diff(SKN_Totrep), TRUE, swarm_label = 'LRS', raw_marker_spread = 1, custom_palette = 'npg', swarm_x_text = 12, swarm_y_text = 12, contrast_y_text = 12, contrast_x_text = 12, raw_marker_alpha = 0.3, tufte_size = 1)
LRS_SKN


#combine all skn-1 reproduction plots
SKN_repro <- ggarrange(SKN_rep+theme(plot.margin = unit(c(0, 1, 0, 0.3), 'cm'))+theme(legend.position = 'none'), 
          ggarrange(Lambda_plot_SKN+left_right_margin, LRS_SKN+left_right_margin, ncol = 2, labels = c('E','F')),
          nrow = 2, heights = c(1.4,1), labels = c('D',''))

SKN_repro

```

## SKN-1 reproduction analysis
```{r}

#set day as numeric variable to square for quadratic term
SKN$Day <- as.numeric(SKN$Day)
SKN$Day2 <- (SKN$Day)^2

#set reference level to ev
SKN$Treatment <- as.factor(SKN$Treatment)
SKN$Treatment <- relevel(SKN$Treatment, ref = 'ev')

#try nbinom2 first with Day^2 included as predictor
m1 <- glmmTMB(value ~ Treatment*Day2+Treatment*Day + (1|ID), family = nbinom2(), data = SKN)
summary(m1)
sim_m1 <- simulateResiduals(m1, plot = T)
testDispersion(sim_m1) #underdispersion
testZeroInflation(sim_m1)#zero inflation issues

#try including ziformula
m2 <- glmmTMB(value ~ Treatment*Day2+Treatment*Day + (1|ID), ziformula = ~Treatment*Day, family = nbinom2(), data = SKN)
summary(m2)
sim_m2 <- simulateResiduals(m2, plot = T)
testZeroInflation(sim_m2)#still major zero inflation
AIC(m1, m2)

#try day^2 in ziformula
m3 <- glmmTMB(value ~ Treatment*Day2 + Treatment*Day + (1|ID), ziformula = ~Treatment*Day2, family = nbinom2(), data = SKN)
summary(m3)
AIC(m2, m3)
sim_m3 <- simulateResiduals(m3, plot = T)
testZeroInflation(sim_m3)#no improvement


#try poisson
m4 <- glmmTMB(value ~ Treatment*Day2 + Treatment*Day +(1|ID), ziformula = ~Treatment*Day2,family = poisson, data = SKN)
AIC(m3, m4)
sim_m4 <- simulateResiduals(m4, plot = T)
testZeroInflation(sim_m4)#improved, but still zero inflation
testDispersion(sim_m4)
summary(m4)


m5 <- glmmTMB(value ~ Treatment*Day2 + Treatment*Day +(1|ID), ziformula = ~Day,family = poisson, data = SKN)
sim_m5 <- simulateResiduals(m5, plot = T)
testZeroInflation(sim_m5)#fixed
testDispersion(sim_m5)#fixed
summary(m5)
AIC(m4, m5)
Anova(m5, type = 'III')

#analyse total reproduction
hist(SKN_totalrep$Totrep)
LRS_m1 <- lm(Totrep ~ Treatment, data = SKN_totalrep)
summary(LRS_m1)

#analyse lambda
hist(SKN_Data$Lambda)
lambda_m1 <- lm(Lambda ~ Treatment, data = SKN_Data)
summary(lambda_m1)


```

## SKN-1 mutant lifespan
```{r}

#get only skn-1 DATA
SKN_LS <- mut_LS %>%
  filter(Strain == 'SKN')

#create survival object
surv<-survfit(Surv(Age,Event)~Treatment,data=SKN_LS)

#survival plot
SKN_LS_plot <-ggsurvplot(surv, ylab="Survival probability", data = SKN_LS, size= 0.8, font.ylab= 13, font.xlab= 13, legend = c(0.8, 0.8), legend.labs = c( "ev", "daf-2"), 
legend.title = "", title = skn1_label, censor = FALSE, xlab = "Day", xlim=c(0,60), break.time.by = 10, position= position_dodge(0.9), font.tickslab = c(12), font.legend = c(13))

#add colours and labels
SKN_LS_plot <- SKN_LS_plot$plot+
  scale_colour_manual(labels = c('ev',daf_label), , values = c('#E64B35FF','#4DBBD5FF'))

SKN_LS_plot

#Censor matricides
SKN_LS_matcen <- SKN_LS %>%
  filter(Cause != 'M')


#create survival object
surv<-survfit(Surv(Age,Event)~Treatment,data=SKN_LS_matcen)

#survival plot
SKN_LS_matcen_plot <-ggsurvplot(surv, ylab="Survival probability", data = SKN_LS_matcen, size= 0.8, font.ylab= 13, font.xlab= 13, legend = c(0.8, 0.8), legend.labs = c( "ev", "daf-2"),  legend.title = "", title = skn1_label, censor = FALSE, xlab = "Day", xlim=c(0,60), break.time.by = 10, position= position_dodge(0.9), font.tickslab = c(12), font.legend = c(13))

#add colours and labels
SKN_LS_matcen_plot <- SKN_LS_matcen_plot$plot+
  scale_colour_manual(labels = c('ev',daf_label), , values = c('#E64B35FF','#4DBBD5FF'))

SKN_LS_matcen_plot


### Analysis with cox proportional hazards model - used for plotting too
cox_SKN <- coxme(Surv(Age, Event) ~ Treatment + (1|Plate.ID), data = SKN_LS)
summary(cox_SKN)
plot(cox.zph(cox_SKN))#looks OK
cox.zph(cox_SKN)#not great, but plot is OK


#Use emmeans because of negligible effect of plate.ID
SKN_emm <- emmeans(cox_SKN, ~ Treatment)  # EMMs of treatment 
SKN_emm

#Get contrasts
contrasts_SKN <- contrast(SKN_emm, method = "revpairwise")

#make a dataframe out of the contrast summary
df_SKN <- as.data.frame(summary(contrasts_SKN, infer = TRUE))

# Rename columns
names(df_SKN)[names(df_SKN) == "estimate"] <- "logHR"
df_SKN$HR <- exp(df_SKN$logHR)
df_SKN$lower.HR <- exp(df_SKN$asymp.LCL)
df_SKN$upper.HR <- exp(df_SKN$asymp.UCL)

#fix labels
df_SKN$Comparison <- df_SKN$contrast

#Create forest plot for differences of treatments within strains
SKN_contrasts <- ggplot(df_SKN, aes(x = Comparison, y = logHR)) +
  geom_point(size = 4, color = '#4DBBD5FF') +
  geom_hline(yintercept = 0, linetype = "dashed", size = 1.2, color = '#E64B35FF', linewidth = 0.8) +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL), width = 0.2, size = 1.1,color ='#4DBBD5FF')+
  coord_flip() +
  scale_x_discrete(labels = c(''))+
  labs(
    title = "",
    x = "",
    y = "Log hazard ratio (HR)"
  ) +
  theme_minimal(base_size = 12)+
  theme(axis.text = element_text(size = 13),
        axis.title = element_text(size = 14),
      axis.line.x = ggplot2::element_line(color = "black", size = 0.5),
      axis.line.y = ggplot2::element_line(color = "black", size = 0.5),
        legend.position = 'none')

SKN_contrasts



#create forest plot
forest_SKN <- meforest(cox_SKN, 'control')
forest_SKN

#cox.ph analysis
cox_SKN_matcen <- coxme(Surv(Age, Event) ~ Treatment + (1|Plate.ID), data = SKN_LS_matcen)
summary(cox_SKN_matcen)
plot(cox.zph(cox_SKN_matcen))
cox.zph(cox_SKN_matcen)#ok

#create forest plot
forest_SKN_matcen <- meforest(cox_SKN_matcen, 'control')
forest_SKN_matcen


#Use emmeans because of negligible effect of plate.ID
SKN_NM_emm <- emmeans(cox_SKN_matcen, ~ Treatment)  # EMMs of treatment 
SKN_NM_emm

#Get contrasts
contrasts_SKN_NM <- contrast(SKN_NM_emm, method = "revpairwise")

#make a dataframe out of the contrast summary
df_SKN_NM <- as.data.frame(summary(contrasts_SKN_NM, infer = TRUE))

# Rename columns
names(df_SKN_NM)[names(df_SKN_NM) == "estimate"] <- "logHR"
df_SKN_NM$HR <- exp(df_SKN_NM$logHR)
df_SKN_NM$lower.HR <- exp(df_SKN_NM$asymp.LCL)
df_SKN_NM$upper.HR <- exp(df_SKN_NM$asymp.UCL)

#fix labels
df_SKN_NM$Comparison <- df_SKN_NM$contrast

#Create forest plot for differences of treatments within strains
SKN_NM_contrasts <- ggplot(df_SKN_NM, aes(x = Comparison, y = logHR)) +
  geom_point(size = 4, color = '#4DBBD5FF') +
  geom_hline(yintercept = 0, linetype = "dashed", size = 1.2, color = '#E64B35FF', linewidth = 0.8) +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL), width = 0.2, size = 1.1,color ='#4DBBD5FF')+
  coord_flip() +
  scale_x_discrete(labels = c(''))+
  labs(
    title = "",
    x = "",
    y = "Log hazard ratio (HR)"
  ) +
  theme_minimal(base_size = 12)+
  theme(axis.text = element_text(size = 13),
        axis.title = element_text(size = 14),
      axis.line.x = ggplot2::element_line(color = "black", size = 0.5),
      axis.line.y = ggplot2::element_line(color = "black", size = 0.5),
        legend.position = 'none')

SKN_NM_contrasts

#combine plots
SKN_mat_inc <- ggarrange(SKN_LS_plot, SKN_contrasts+theme(plot.margin = margin(t = 0, r = 0.15, b = 0, l = 0.75, unit = "cm")), nrow = 2, ncol = 1, heights = c(2,1), labels = c('B','E'), common.legend = T)
SKN_mat_inc

SKN_mat_exc <- ggarrange(SKN_LS_matcen_plot, SKN_NM_contrasts+theme(plot.margin = margin(t = 0, r = 0.15, b = 0, l = 0.75, unit = "cm")), nrow = 2, ncol = 1, heights = c(2,1), labels = c('B','E'), common.legend = T)
SKN_mat_exc

```

## DAF-16 mutant reproduction plot
```{r}

#Age-specific reproduction plot
 DAF16_rep <-ggplot(data=DAF16, aes(x=factor(Day), y=value, group=Treatment, color=Treatment))+
  geom_jitter(alpha = 0.2, position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.5))+
  stat_summary(fun.data="mean_cl_boot", geom="errorbar", size = 1, width=0.0, position = position_dodge(0.5)) +
  stat_summary(fun.data="mean_cl_boot", geom="point", size = 3, position = position_dodge(0.5)) +
  stat_summary(fun.data="mean_cl_boot", geom="line",  size=1, position = position_dodge(0.5)) +
  theme_classic()+
  labs(y="Offspring number", x="Day", size=13)+
  labs(col="")+
  labs(title = daf16_label)+
  theme(axis.title.y = element_text(size=14),
        axis.text.y = element_text(size = 12))+
  theme(axis.title.x = element_text(size=14),
        axis.text.x = element_text(size = 12),
        title = element_text(size = 14))+
  theme(legend.text = element_text(size = 12))+
  scale_color_manual(values=c('#E64B35FF','#4DBBD5FF'),, labels = c('ev', daf_label))+
  theme(legend.key.width = unit(0.5,"cm"))+
  coord_cartesian(ylim = c(0,85))+
  theme(legend.position = c(0.8,0.9))
 
DAF16_rep

##################
# calculate individual fitness
#################

#spread data back out
DAF16_wide <- spread(DAF16, Day, value)

#remove unnecessary columns
within(DAF16_wide, rm(Strain))

#create empty matrix
L <- matrix(nrow = nrow(DAF16_wide), ncol = 3)

#create loop to calculate individual fitness
for (i in 1:nrow(DAF16_wide)){
  Les <- matrix(0, ncol = 9, nrow = 9)
  diag(Les[-1,]) <- rep(1, 8) # add the 1s for survival probability diagonally
  Fert <- c(0,0, as.numeric(as.vector(DAF16_wide[i,][4:10]))) #the columns in data that has the reproductive counts
  Fert[is.na(Fert)] <- 0 #makes all NAs into 0
  Les[1,] <- c(Fert)
  class(Les) <- "leslie.matrix"
  Lambda <- popbio::eigen.analysis(Les)$lambda1
  L[i, 1:3] <- c(paste0(DAF16_wide$Treatment[i]), paste0(DAF16_wide$ID[i]), Lambda)
  
}

#change column names
colnames(L)<-c("Treatment", "ID", "Lambda")

#set lambda values as dataframe
DAF16_Data<-as.data.frame(L)

#make sure lambda is numeric
DAF16_Data$Lambda<-as.numeric(as.character(DAF16_Data$Lambda))

#create dabestr object
Lambda_DAF16 <-
  DAF16_Data %>%
  load(Treatment, Lambda,
         idx = list(c("control", "daf-2")))

## Lambda dabestr plot
Lambda_plot_DAF16 <- dabest_plot(mean_diff(Lambda_DAF16), TRUE, swarm_label = 'Lambda', raw_marker_spread = 1, custom_palette = 'npg', swarm_x_text = 12, swarm_y_text = 12, contrast_y_text = 12, contrast_x_text = 12, raw_marker_alpha = 0.3, tufte_size = 1)

Lambda_plot_DAF16

#######################
# calcualte LRS
######################

#calculate total offspring produced per individual over all days
DAF16_totalrep<-na.omit(as.data.frame.table(tapply(DAF16$value,list(DAF16$Treatment, DAF16$ID),sum)))

#change column names
names(DAF16_totalrep)<-c("Treatment", "Replicate", "Totrep")

#create dabestr object
DAF16_Totrep <-
  DAF16_totalrep %>%
  load(Treatment, Totrep,
         idx = c('control','daf-2'))

#LRS plot
LRS_DAF16 <- dabest_plot(mean_diff(DAF16_Totrep), TRUE, swarm_label = 'LRS', raw_marker_spread = 1, custom_palette = 'npg', swarm_x_text = 12, swarm_y_text = 12, contrast_y_text = 12, contrast_x_text = 12, raw_marker_alpha = 0.3, tufte_size = 1)

LRS_DAF16

#combine all daf-16 repro plots
DAF16_repro <- ggarrange(DAF16_rep+theme(plot.margin = unit(c(0, 1, 0, 0.3), 'cm'))+theme(legend.position = 'none'), 
          ggarrange(Lambda_plot_DAF16+left_right_margin, LRS_DAF16+left_right_margin, ncol = 2, labels = c('H','I')),
          nrow = 2, heights = c(1.4, 1), labels = c('G',''))

DAF16_repro

```

## DAF16 reproduction analysis
```{r}

#set day as numeric variable to square for quadratic term
DAF16$Day <- as.numeric(DAF16$Day)
DAF16$Day2 <- (DAF16$Day)^2

#set reference level to ev
DAF16$Treatment <- as.factor(DAF16$Treatment)
DAF16$Treatment <- relevel(DAF16$Treatment, ref = 'ev')

#try nbinom2 first with Day^2 included as predictor
m1 <- glmmTMB(value ~ Treatment*Day2+Treatment*Day + (1|ID), family = nbinom2(), data = DAF16)
summary(m1)
sim_m1 <- simulateResiduals(m1, plot = T)
testDispersion(sim_m1) #underdispersion
testZeroInflation(sim_m1)#zero inflation issues

#try including ziformula
m2 <- glmmTMB(value ~ Treatment*Day2+Treatment*Day + (1|ID), ziformula = ~Treatment*Day, family = nbinom2(), data = DAF16)
summary(m2)
sim_m2 <- simulateResiduals(m2, plot = T)
testZeroInflation(sim_m2)#still major zero inflation
AIC(m1, m2)

#try day^2 in ziformula
m3 <- glmmTMB(value ~ Treatment*Day2 + Treatment*Day + (1|ID), ziformula = ~Treatment*Day2, family = nbinom2(), data = DAF16)
summary(m3)
AIC(m2, m3)
sim_m3 <- simulateResiduals(m3, plot = T)
testZeroInflation(sim_m3)#no improvement


#try poisson
m4 <- glmmTMB(value ~ Treatment*Day2 + Treatment*Day +(1|ID), ziformula = ~Treatment*Day2,family = poisson, data = DAF16)
AIC(m3, m4)
sim_m4 <- simulateResiduals(m4, plot = T)
testZeroInflation(sim_m4)#fixed
testDispersion(sim_m4)# overdispersed
summary(m4)


#use this
m5 <- glmmTMB(value ~ Treatment*Day2 + Treatment*Day +(1|ID), ziformula = ~Day,family = poisson, data = DAF16)
sim_m5 <- simulateResiduals(m5, plot = T)
testZeroInflation(sim_m5)#fixed
testDispersion(sim_m5)#slightly overdispersed, but much better
summary(m5)
AIC(m4, m5)
Anova(m5, type = 'III')

#try removing ziformula
m6 <- glmmTMB(value ~ Treatment*Day2 + Treatment*Day +(1|ID), family = poisson, data = DAF16)
sim_m6 <- simulateResiduals(m6, plot = T)
testZeroInflation(sim_m6)#bad
testDispersion(sim_m6)#bad
summary(m6)
AIC(m5, m6)

#analyse total reproduction
hist(DAF16_totalrep$Totrep)
LRS_m1 <- lm(Totrep ~ Treatment, data = DAF16_totalrep)
summary(LRS_m1)

#analyse lambda
hist(DAF16_Data$Lambda)
lambda_m1 <- lm(Lambda ~ Treatment, data = DAF16_Data)
summary(lambda_m1)

```

## DAF-16 mutant lifespan
```{r}
#get DAF16 only
DAF16_LS <- mut_LS %>%
  filter(Strain == 'DAF16')


#create survival object
surv<-survfit(Surv(Age,Event)~Treatment,data=DAF16_LS)

#creat survival plot
DAF16_LS_plot <-ggsurvplot(surv, ylab="Survival probability", data = DAF16_LS, size= 0.8, font.ylab= 13, font.xlab= 13, legend = 'none', legend.labs = c( "ev", "daf-2"), 
legend.title = "", title = daf16_label, censor = FALSE, xlab = "Day", xlim=c(0,60), break.time.by = 10, position= position_dodge(0.9), font.tickslab = c(12), font.legend = c(13))

#fix colours and labels
DAF16_LS_plot <- DAF16_LS_plot$plot+
  scale_colour_manual(labels = c('ev',daf_label), , values = c('#E64B35FF','#4DBBD5FF'))

DAF16_LS_plot

#Censor matricides
DAF16_LS_matcen <- DAF16_LS %>%
  filter(Cause != 'M')

#create survival objecct
surv<-survfit(Surv(Age,Event)~Treatment,data=DAF16_LS_matcen)

#create survival plot
DAF16_LS_matcen_plot <-ggsurvplot(surv, ylab="Survival probability", data = DAF16_LS_matcen, size= 0.8, font.ylab= 13, font.xlab= 13, legend = 'none', legend.labs = c( "ev", 'daf-2'),  legend.title = "", title = daf16_label, censor = FALSE, xlab = "Day", xlim=c(0,60), break.time.by = 10, position= position_dodge(0.9), font.tickslab = c(12), font.legend = c(13))

#add colours and labels
DAF16_LS_matcen_plot <- DAF16_LS_matcen_plot$plot+
  scale_colour_manual(labels = c('control',daf_label), , values = c('#E64B35FF','#4DBBD5FF'))

DAF16_LS_matcen_plot

#cox proportional hazards model
cox_DAF16 <- coxme(Surv(Age, Event) ~ Treatment + (1|Plate.ID), data = DAF16_LS)
summary(cox_DAF16)
cox.zph(cox_DAF16)#OK



#Use emmeans because of negligible effect of plate.ID
DAF16_emm <- emmeans(cox_DAF16, ~ Treatment)  # EMMs of treatment 
DAF16_emm

#Get contrasts
contrasts_DAF16 <- contrast(DAF16_emm, method = "revpairwise")

#make a dataframe out of the contrast summary
df_DAF16 <- as.data.frame(summary(contrasts_DAF16, infer = TRUE))

# Rename columns
names(df_DAF16)[names(df_DAF16) == "estimate"] <- "logHR"
df_DAF16$HR <- exp(df_DAF16$logHR)
df_DAF16$lower.HR <- exp(df_DAF16$asymp.LCL)
df_DAF16$upper.HR <- exp(df_DAF16$asymp.UCL)

#fix labels
df_DAF16$Comparison <- df_DAF16$contrast

#Create forest plot for differences of treatments within strains
DAF16_contrasts <- ggplot(df_DAF16, aes(x = Comparison, y = logHR)) +
  geom_point(size = 4, color = '#4DBBD5FF') +
  geom_hline(yintercept = 0, linetype = "dashed", size = 1.2, color = '#E64B35FF', linewidth = 0.8) +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL), width = 0.2, size = 1.1,color ='#4DBBD5FF')+
  coord_flip() +
  scale_x_discrete(labels = c(''))+
  labs(
    title = "",
    x = "",
    y = "Log hazard ratio (HR)"
  ) +
  theme_minimal(base_size = 12)+
  theme(axis.text = element_text(size = 13),
        axis.title = element_text(size = 14),
      axis.line.x = ggplot2::element_line(color = "black", size = 0.5),
      axis.line.y = ggplot2::element_line(color = "black", size = 0.5),
        legend.position = 'none')

DAF16_contrasts



#create forest plot
forest_DAF16 <- meforest(cox_DAF16, 'control')
forest_DAF16

#cox proportional hazards model
cox_DAF16_matcen <- coxme(Surv(Age, Event) ~ Treatment + (1|Plate.ID), data = DAF16_LS_matcen)
summary(cox_DAF16_matcen)
cox.zph(cox_DAF16_matcen)



#Use emmeans because of negligible effect of plate.ID
DAF16_NM_emm <- emmeans(cox_DAF16_matcen, ~ Treatment)  # EMMs of treatment 
DAF16_NM_emm

#Get contrasts
contrasts_DAF16_NM <- contrast(DAF16_NM_emm, method = "revpairwise")

#make a dataframe out of the contrast summary
df_DAF16_NM <- as.data.frame(summary(contrasts_DAF16_NM, infer = TRUE))

# Rename columns
names(df_DAF16_NM)[names(df_DAF16_NM) == "estimate"] <- "logHR"
df_DAF16_NM$HR <- exp(df_DAF16_NM$logHR)
df_DAF16_NM$lower.HR <- exp(df_DAF16_NM$asymp.LCL)
df_DAF16_NM$upper.HR <- exp(df_DAF16_NM$asymp.UCL)

#fix labels
df_DAF16_NM$Comparison <- df_DAF16_NM$contrast

#Create forest plot for differences of treatments within strains
DAF16_NM_contrasts <- ggplot(df_DAF16_NM, aes(x = Comparison, y = logHR)) +
  geom_point(size = 4, color = '#4DBBD5FF') +
  geom_hline(yintercept = 0, linetype = "dashed", size = 1.2, color = '#E64B35FF', linewidth = 0.8) +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL), width = 0.2, size = 1.1,color ='#4DBBD5FF')+
  coord_flip() +
  scale_x_discrete(labels = c(''))+
  labs(
    title = "",
    x = "",
    y = "Log hazard ratio (HR)"
  ) +
  theme_minimal(base_size = 12)+
  theme(axis.text = element_text(size = 13),
        axis.title = element_text(size = 14),
      axis.line.x = ggplot2::element_line(color = "black", size = 0.5),
      axis.line.y = ggplot2::element_line(color = "black", size = 0.5),
        legend.position = 'none')

DAF16_NM_contrasts

#create forest plot
forest_DAF16_matcen <- meforest(cox_DAF16_matcen, 'control')
forest_DAF16_matcen

#combine plots
DAF16_mat_inc <- ggarrange(DAF16_LS_plot +theme(legend.position = 'none'), DAF16_contrasts+theme(plot.margin = margin(t = 0, r = 0.15, b = 0, l = 0.75, unit = "cm")), nrow = 2, ncol = 1, heights = c(2,1), labels = c('C','F'))
DAF16_mat_inc

DAF16_mat_exc <- ggarrange(DAF16_LS_matcen_plot +theme(legend.position = 'none'), DAF16_NM_contrasts+theme(plot.margin = margin(t = 0, r = 0.15, b = 0, l = 0.75, unit = "cm")), nrow = 2, ncol = 1, heights = c(2,1), labels = c('C','F'))
DAF16_mat_exc


```

# combine lifespan and reproduction plots
```{r}

##############
# LIFESPAN
##############

#excluding matricides (main text)
all_LS_mat_exc <- ggarrange(N2_mat_exc+theme(plot.margin = margin(1,0,0,0, 'cm')), SKN_mat_exc, DAF16_mat_exc+theme(plot.margin = margin(1,0,0,0, 'cm')), ncol = 3, nrow = 1)
all_LS_mat_exc

ggsave(plot = all_LS_mat_exc, 'all_LS_mat_exc.png', height = 5, width = 9, bg = 'white')


#including matricides (supp mat)
all_LS_mat_inc <- ggarrange(N2_mat_inc+theme(plot.margin = margin(1,0,0,0, 'cm')), SKN_mat_inc, DAF16_mat_inc+theme(plot.margin = margin(1,0,0,0, 'cm')), ncol = 3, nrow = 1)
all_LS_mat_inc

ggsave(plot = all_LS_mat_inc, 'all_LS_mat_inc.png', height = 5, width = 9, bg = 'white')


##############
# REPRODUCTION
##############

all_repro <- ggarrange(N2_rep, SKN_rep , DAF16_rep, nrow = 3, ncol = 1, common.legend = T, labels = c('A','B','C'))
all_repro

ggsave(plot = all_repro, 'all_repro.png', height = 9, width = 6, bg = 'white')


```

#Temperature Plot
```{r}

head(temp)


# Convert to datetime (add a dummy date)
temp$Time <- as.POSIXct(paste("2026-01-01", temp$Time), format = "%Y-%m-%d %H:%M")

# Create shifted time (preserve POSIXct class)
temp$Time_shifted <- temp$Time
temp$Time_shifted[format(temp$Time, "%H") < "05"] <- 
  temp$Time_shifted[format(temp$Time, "%H") < "05"] + 86400

# Convert back to POSIXct (ifelse turns it numeric)
temp$Time_shifted <- as.POSIXct(temp$Time_shifted, origin = "1970-01-01")


# Plot
temp_plot <- ggplot(temp, aes(x = Time_shifted, y = Temp)) +
  geom_line(color = 'skyblue2', linewidth = 1.2) +
  #geom_point(color = 'cornflowerblue') +
  scale_x_datetime(
    date_breaks = "4 hours",
    date_labels = "%H:%M"
  ) +
  labs(
    x = "Time",
    y = "Temperature (°C)"
  ) +
  theme_minimal()


temp_plot

ggsave(plot = temp_plot, 'temp_plot.png', height = 3, width = 6, bg = 'white')

```
